title: My super cool thing
author: Sunil Dass
email: sunildass2002@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  baseurl: This description is great, one of the best.

# social links
twitter_username: mylzad # DO NOT include the @ character, or else the build will fail!
github_username:  zeusakadelta # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
