title: The Portfolio of Sunil Dass
theme: minima
author: Sunil Dass
email: sunildass2002@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is all previous works done by Sunil Dass in the
  Computer Science industry

# social links
twitter_username: mylzad # DO NOT include the @ character, or else the build will fail!
github_username:  zeusakadelta # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
